source("~/GitHub/SofiaWL/ReplicationPackage/WorkloadMeasures/CumulativePercentageLib.r")

openActual <- read.csv('~/GitHub/SofiaWL/ReplicationPackage/Data/Workload/Actual/OpenReviewsPerQuarter.csv', header = T)
openAuthRec <- read.csv('~/GitHub/SofiaWL/ReplicationPackage/Data/Workload/Simulated/OpenReviewsAuthRecPerQuarter.csv', header = T)
openOwnRec <- read.csv('~/GitHub/SofiaWL/ReplicationPackage/Data/Workload/Simulated/OpenReviewsOwnRecPerQuarter.csv', header = T)
opencH <- read.csv('~/GitHub/SofiaWL/ReplicationPackage/Data/Workload/Simulated/OpenReviewscHRevPerQuarter.csv', header = T)
openLearnRec <- read.csv('~/GitHub/SofiaWL/ReplicationPackage/Data/Workload/Simulated/OpenReviewsLearnRecPerQuarter.csv', header = T)
openRet <- read.csv('~/GitHub/SofiaWL/ReplicationPackage/Data/Workload/Simulated/OpenReviewsRetentionRecPerQuarter.csv', header = T)
openTurnRec <- read.csv('~/GitHub/SofiaWL/ReplicationPackage/Data/Workload/Simulated/OpenReviewsTurnRecPerQuarter.csv', header = T)
sofiaICSE <- read.csv('~/GitHub/SofiaWL/ReplicationPackage/Data/Workload/Simulated/OpenReviewsSofiaICSEPerQuarter.csv', header = T)
openWhoDo <- read.csv('~/GitHub/SofiaWL/ReplicationPackage/Data/Workload/Simulated/OpenReviewsWhoDoPerQuarter.csv', header = T)
sofiaWL <- read.csv('~/GitHub/SofiaWL/ReplicationPackage/Data/Workload/Simulated/OpenReviewsSofiaWLPerQuarter.csv', header = T)

# workload difference in area of actual to simulated (the reported numbers in the table and paper)
auc_difference_percentage_all(openActual, openAuthRec)
auc_difference_percentage_all(openActual, openOwnRec)
auc_difference_percentage_all(openActual, opencH)
auc_difference_percentage_all(openActual, openLearnRec)
auc_difference_percentage_all(openActual, openRet)
auc_difference_percentage_all(openActual, openTurnRec)
auc_difference_percentage_all(openActual, sofiaICSE)
auc_difference_percentage_all(openActual, openWhoDo)
auc_difference_percentage_all(openActual, sofiaWL)

# cumulative workload at p, eg p = 20, is the cumulative workload of the top 20% of devs
p = 20
cumulative_at_p_all(openActual, p)
cumulative_at_p_all(openAuthRec, p)
cumulative_at_p_all(openOwnRec, p)
cumulative_at_p_all(opencH, p)
cumulative_at_p_all(openLearnRec, p)
cumulative_at_p_all(openRet, p)
cumulative_at_p_all(openTurnRec, p)
cumulative_at_p_all(sofiaICSE, p)
cumulative_at_p_all(openWhoDo, p)
cumulative_at_p_all(sofiaWL, p)



# plot to show area differences in background methodology
#pdf("~/Downloads/WorkloadAUCExample.pdf")
plot(seq(1:100), seq(1:100), type = 'l', lwd = 3, lty = "twodash", ylab = "Cumulative Percentage of Reviews", xlab = "Percentage of Reviewers")
plot_line_percentage_percentage(percentage_percentage_freq(openActual$Kubernetes), lty = "solid")
plot_line_percentage_percentage(percentage_percentage_freq(openOwnRec$Kubernetes), lty = "dotted", pch = 2)
plot_line_percentage_percentage(percentage_percentage_freq(openWhoDo$Kubernetes), lty = "dashed", pch = 6)
abline(v = 20)
legend(50, 20, legend=c("Past Reviewers Rec", "Actual Workload", "Workload Aware Rec", "Perfectly Equal Workload"), lty=c('dotted', 'solid', 'dashed', 'twodash'), lwd = 3, cex=1.2)
#dev.off()

# discussion plot (replace Rust with any other project to see results for different projects)
#pdf("~/Downloads/WorkloadAUCDiscussion.pdf")
plot(seq(1:100), seq(1:100), type = 'l', lwd = 3, lty = "solid", ylab = "Cumulative Percentage of Reviews", xlab = "Percentage of Reviewers")
plot_line_percentage_percentage(percentage_percentage_freq(openActual$Rust), lty = "solid")
plot_line_percentage_percentage(percentage_percentage_freq(openOwnRec$Rust), lty = "dotted", pch = 2)
plot_line_percentage_percentage(percentage_percentage_freq(sofiaWL$Rust), lty = "twodash", pch = 6)
plot_line_percentage_percentage(percentage_percentage_freq(openWhoDo$Rust), lty = "dashed", pch = 6)
#plot_line_percentage_percentage(percentage_percentage_freq(openLearnRec$Rust), lty = "dashed", pch = 6)
abline(v = 1.5)
abline(v = 10)
abline(v = 20)
abline(h = 80)
abline(h = 60)
abline(h = 20)
legend(50, 20, legend=c("RevOwnRec", "Actual Workload", "SofiaWL", "WhoDo", "x = y"), lty=c('dotted', 'solid', 'twodash', 'dashed', 'solid'), lwd = 3, cex=1.2)
#dev.off()

